/**
 * Canonical environment variable names — see docs/portal/ENV_CONTRACT.md for semantics.
 */
export const EnvKeys = {
  AZURE_RESOURCE_GROUP: 'AZURE_RESOURCE_GROUP',
  DATABASE_URL: 'DATABASE_URL',
  BLOB_CONNECTION_STRING: 'BLOB_CONNECTION_STRING',
  BLOB_ACCOUNT_URL: 'BLOB_ACCOUNT_URL',
  ACS_CONNECTION_STRING: 'ACS_CONNECTION_STRING',
  GEMINI_API_KEY: 'GEMINI_API_KEY',
  ENTRA_TENANT_ID: 'ENTRA_TENANT_ID',
  ENTRA_API_AUDIENCE: 'ENTRA_API_AUDIENCE',
  ENTRA_ISSUER: 'ENTRA_ISSUER',
  CORS_ALLOWED_ORIGINS: 'CORS_ALLOWED_ORIGINS',
  FEATURE_HAR_IDX_SYNC: 'FEATURE_HAR_IDX_SYNC',
  FEATURE_VENDOR_PORTAL: 'FEATURE_VENDOR_PORTAL',
  FEATURE_APPLY_API_DEFAULT: 'FEATURE_APPLY_API_DEFAULT',
} as const;

export type EnvKey = (typeof EnvKeys)[keyof typeof EnvKeys];

/** Required resource group name for this project. */
export const REQUIRED_RESOURCE_GROUP = 'carwoods.com';
