name: Trigger auto deployment for carwoods-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/carwoods-app-AutoDeployTrigger-9dcabda0-5a06-4445-9bec-f2f6be471bc9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CARWOODSAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CARWOODSAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CARWOODSAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CARWOODSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARWOODSAPP_REGISTRY_PASSWORD }}
          containerAppName: carwoods-app
          resourceGroup: carwoods
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


