name: Trigger auto deployment for carwoods-app

on:
  push:
    branches:
      [ main ]
    paths:
    - '**'
    - '.github/workflows/carwoods-app-AutoDeployTrigger-8805f666-171d-4f69-ae78-9cec2c94685f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/carwoods-app:${{ github.sha }} .
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker push ${{ secrets.REGISTRY_URL }}/carwoods-app:${{ github.sha }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          registryUsername: ${{ secrets.CARWOODSAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CARWOODSAPP_REGISTRY_PASSWORD }}
          containerAppName: carwoods-app
          resourceGroup: carwoods
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
